version: '3'

services:
  web123:
    image: unknownty/4640lab12front
    ports:
      - "8080:80"
    volumes:
      - ./frontend/templates:/etc/nginx/templates
    env_file:
      - variables.env
  app456:
    image: unknownty/4640lab12back
    env_file:
      - variables.env
  database789:
    image: mysql
    volumes:
      - lab11db:/var/lib/mysql
    env_file:
      - variables.env
volumes:
  lab11db: