FROM python

RUN apt-get update -qy
RUN apt-get install -y wait-for-it
RUN pip install gunicorn

# Set the working directory to a matchin /app/ directory
RUN mkdir /backend
RUN mkdir /frontend
WORKDIR /tmp/

COPY . /backend/src
COPY ../frontend/* /frontend

WORKDIR /backend/src
RUN pip install -r ./requirements.txt

EXPOSE ${BACKEND_PORT}


CMD [ "bash", "boot.sh" ]